version: "3.3"

services:
  mysqldb:
    container_name: database
    image: mysql:latest
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - interest-rate-api-network
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: api
    depends_on:
      - mysqldb
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    networks:
      - interest-rate-api-network
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?serverTimezone=UTC&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect.storage_engine" : "innodb"
      }'
    volumes:
      - ./db/mysql:/data/db
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M

volumes:
  db:

networks:
  interest-rate-api-network:
    driver: bridge